+
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-1
  namespace: dev
  labels:
    app: web-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-1
  template:
    metadata:
      labels:
        app: web-app-1
    spec:
      containers:
      - name: web-app-1
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
